### ISSUE TITLE
TODO #1

### ISSUE THREAD

**Issue by yilmazmuhammed** [yilmazmuhammed/Sandikv2#10]
- [ ] Ödemeler sayfasında "Ödenme durumu" filtresi kayboldu. İki filtre aynı anda gösterilemiyor mu?

- [ ] **GENEL**
- [ ] **İŞLEMLER**
  - [x] Ödemeler, borçlar, para işlemleri gibi sayfalarda tablolara üye filtresi eklenecek
  - [ ] Borç ödenmesinde önce başkalarına olan piece_of_debt ödenecek, sonra üyenin kendisine olan borcu ödenecek.
    - [ ] Tek işlemde birden fazla borç oluşursa, üyenin kendi bakiyesi her borca orantılı bölüştürülmeli
- [ ] **SANDIK**
  - [ ] Site kullanıcısı olmadan da sandığa üye eklenebilmesini sağlayan yeni bir üye ekleme sayfası eklenecek (tek seferde hem üye hem site kullanıcısı oluşturulacak)
  - [ ] Sandık/Üye özeti sayfasında hisseler tablosunda verilerdeki hatalar düzeltilecek
  - [ ] Sandık özeti sayfasında;
    - [x] Üye son durumu değerlerinin üzerine gelince hisse hisse ayrıntılar gösterilecek
- [ ] **SANDIK KURALLARI**
  - [x] catch_exception fonksiyonunun dönüşünde bool kontrolü değil, is None kontrolü sağlanması gerekiyor.
- [ ] **BİLDİRİMLER**
  - [ ] Base bildirim class'ı oluştur.
  - [ ] Sms gönderilsin parametresi eklenecek
- [ ] **SMS BİLDİRİMLERİ**
  - [ ] Gönderilen sms paketleri sayfası eklenecek
- [ ] **LOG MEKANİZMASI**

----

- [x] **GENEL**
  - [x] Kullanılmayan sayı rozetleri kaldırılacak
  - [x] Banka hesabı güncelleme formu eklenecek
  - [x] Parola değiştirme formu eklenecek
- [x] **İŞLEMLER**
  - [x] Özel aidat silme özelliği eklenecek
  - [x] Üyelerin işleme sokulmamış bakiyelerinden, vadesi gelmiş ve ödenmemiş ödemelerinin yapılması için buton eklenecek (Sandıktaki bütün üyelerin hepsine tek seferde uygulanabilmesi için de eklenecek)
  - [x] Para giriş/çıkışları sayfasından üye ismine üye özeti sayfasının bağlantısı eklenecek
  - [x] Ödemeler sayfasında vadesi gelmiş ve ödenmemiş ödemeler tablosu küçükten büyüğe sıralanacak
  - [x] Sandık yönetimi için üye işlemleri sayfası eklenecek 
    - [x]  Üye özeti ve sandık üyeleri sayfalarına üye işlemleri sayfasının bağlantısı eklenecek
- [x] **SANDIK**
  - [x] Sandık yetkilerinde üyenin sandıkta yetkisi yok fakat üye site yöneticisi ise alert ile mesaj gösterilsin, devam etmek istenip istenmediği sorulsun.
  - [x] Sandık yönetimi için üyenin güven halkası sayfası eklenecek
  - [x] Üyelerin her hissesi üzerinden ne kadar ve kaç taksitle borç alabileceği gösterilecek
  - [x] Güven bağı istekleri tablosunda;
    - [x] Güven bağı kurulmamış bütün üyeleri listele. 
    - [x] Aksiyon sütununda istek gönder, geri çek, onayla, reddet butonlarını göster.
    - [x] İsimleri sola hizala
    - [x] Güven halkam ve üye özeti sayfalarında güven halkam tablosunu alfabetik sırala
    - [x] Güven halkam sayfasında güven halkam tablosunda isimler sola dayalı olacak
  - [x] Sandık özeti sayfasında;
    - [x] Klasik sandık tipi için sandığa katkım tablosunda geri ödenen taksit satırı kaldırılacak
- [x] **BİLDİRİMLER**
  - [x] Yeni kullanıcı kaydolduğunda site yöneticilerine bildirim gönderilecek (anonymous@sandik.com)
- [x] **LOG MEKANİZMASI**
  - [x] Log sisteminde ref'lerde üye veya hisse ise hangi kullanıcıya ait olduğu gösterilecek
  - [x] Yeni kullanıcı kaydolduğunda log oluşturulacak (anonymous@sandik.com)
  - [x] Güncelleme loglarında, log detayına sadece değişen özniteliklerin eski ve yeni değerlerinin eklenmesi bütün güncelleme işlemleri için uygulanacak
